### ISSUE TITLE
[Feature] Tape File Explorer: exporting support 

### ISSUE THREAD

**Issue by Ultrahead** [Dotneteer/spectnetide#193] opened 2020-05-02 16:01 UTC
The tape file exporting is really handy.

And it would great if we could export either the disassembled code or, when Basic Code is available, a basic file.

![image](https://user-images.githubusercontent.com/12087040/80869140-f4d64700-8c74-11ea-9f60-841699ac194f.png)

![image](https://user-images.githubusercontent.com/12087040/80869132-ed16a280-8c74-11ea-95b7-26939964778a.png)

**Comment by Dotneteer** [comment] 2020-05-03 05:11
@Ultrahead, I would implement exporting the disassembly soon.

**Comment by Dotneteer** [comment] 2020-05-03 05:13
@Ultrahead, when you mention "BASIC file" you mean a text file or another format?

**Comment by Ultrahead** [comment] 2020-05-03 08:32
I meant the content. Whether you export it as a txt file, a .zxbas one or copy to the clipboarf is ok.

**Comment by Dotneteer** [comment] 2020-05-09 11:40
Here I send you the private build that contains the requested feature. Please, try it and share your experiences with me! I try to release Preview 8 as soon as possible.

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4603374/Spect.Net.VsPackage.zip)

**Comment by Ultrahead** [comment] 2020-05-09 15:52
Hi István, thanks for the build.

I works. The .bas file gets exported. However it does not compile when included in a Project as .zxbas. The compiler starts but never stops. I’m attaching the file for you to see.

So far so good with the build. It works. It would be nice to also include the file in the project. For example, instead of exporting it as .bas, to importing it in the open project as .zxbas. But that for a future release of SpectNetIDE other than preview 8. Right now, it’s enough.

Kind regards,
Pedro

De: Istvan Novak<mailto:notifications@github.com>
Enviado: sábado, mayo 09, 2020 8:40 AM
Para: Dotneteer/spectnetide<mailto:spectnetide@noreply.github.com>
CC: Pedro Güida<mailto:ultrahead@msn.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [Dotneteer/spectnetide] [Feature] Tape File Explorer: exporting support (#193)


Here I send you the private build that contains the requested feature. Please, try it and share your experiences with me! I try to release Preview 8 as soon as possible.

Spect.Net.VsPackage.zip<https://github.com/Dotneteer/spectnetide/files/4603374/Spect.Net.VsPackage.zip>

**Comment by Dotneteer** [comment] 2020-05-09 16:03
Pedro, I intentionally export the BASIC listing to a `.bas` file, as it contains ZX Spectrum BASIC code. The `.zxbas` extension is for ZX BASIC files (it's a different, more featureful syntax than Spectrum BASIC). Apparently, I cannot compile Spectrum BASIC to ZX BASIC.

So, there's a very little likelihood that you'll be able to compile an exported output with ZX BASIC. That is why I do not add the exported file to the project, just save it. You should manually convert it to a ZX BASIC program :-(
Nonetheless, I take a look at the "never-stops-compiling" file you've sent me.

**Comment by Ultrahead** [comment] 2020-05-09 16:11
After 5 minutes a timeout message appeared.

Is there any way to compile standard basic to assembly code with SpectNetIDE? (I know I can use the emulator to type each line the old way)

**Comment by Dotneteer** [comment] 2020-05-09 16:17
By compile, you mean importing a `.bas` file into the ZX Spectrum machine, just as you typed it? 

So far, there's no such a feature in SpectNetIDE, but probably it is worth to create it :-). If you have ideas, how you'd like to use it, just add a new feature request to the project :-).

**Comment by Ultrahead** [comment] 2020-05-09 16:19
Actually I mean to compile that .bas into assembly code and run the latter (as you do with ZX Basic).

**Comment by Dotneteer** [comment] 2020-05-09 16:23
Ohhh... I see. I do not know any compiler that does this. This is why ZX BASIC is integrated in SpectNetIDE. Well, if you know any utility that does this compilation, let me know, I test whether I can integrate it into SpectNetIDE. 
I could not undertake writing such a compiler on my own, it would take me a year or more...

**Comment by Ultrahead** [comment] 2020-05-09 16:31
ZX basic supports most of standard basic programs with no modifications. This one is an exception :)

No problem.

**Comment by Ultrahead** [comment] 2020-05-09 16:48
José tells me that in order to increase compatibility ratio --sinclair should be added

**Comment by Ultrahead** [comment] 2020-05-09 16:54
But there is a problem with the graphic characters: "°97°°97° ..."

https://zxbasic.readthedocs.io/en/latest/syntax/?fbclid=IwAR1tZr6TLGsQXpJNSq25Qr0Xtbjzfwrno9BK0JzjtUHHB5O7DQG-g-LqP64#graphic-characters

**Comment by Dotneteer** [comment] 2020-05-10 05:26
Thanks for the suggestions, I look after them :-)

**Comment by boriel** [comment] 2020-05-10 11:54
Hi!!
I've also located at least 2 bugs within ZX Basic that will prevent this program to compile :(
I've fixed one of them already, the other is on the way. Thanks for your patience. Will provide a new release ASAP.

**Comment by Dotneteer** [comment] 2020-05-10 12:29
@boriel, thanks for finding the bug! I like the strength og the community :-)

**Comment by Dotneteer** [comment] 2020-05-10 16:22
Pedro, here is the next private build with tiny new features:
- You can choose between *Sinclair* and *ZX BASIC* modes for displaying control characters.
- Now, ZX BASIC compilation does not hang.
- The `--sinclair` command-line option is automatically used when invoking ZXB.

See modified docs here:
- https://dotneteer.github.io/spectnetide/getting-started/list-basic-program#article
- https://dotneteer.github.io/spectnetide/documents/tape-explorer-commands#article

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4606066/Spect.Net.VsPackage.zip)

**Comment by boriel** [comment] 2020-05-10 18:33
Also, if there's a compilation that makes the compiler to hang, etc. please let me know!

**Comment by Ultrahead** [comment] 2020-05-10 19:15
@boriel please let me know when the new version is up with the fixes so I can download it and re-test

**Comment by boriel** [comment] 2020-05-10 21:25
@Dotneteer Just one thing: `--sinclair` is good for people coming from Sinclair BASIC because it will ease the transition, but it's not mandatory to be used to produce compatible code. In other words it should be used when porting an old Sinclair BASIC program (at the cost of somewhat reduced performance)

**Comment by boriel** [comment] 2020-05-10 21:25
Okay, here is a (preliminary) fixed version:
http://www.boriel.com/files/zxb/zxbasic-1.10.0-beta5-win32.zip
http://www.boriel.com/files/zxb/zxbasic-1.10.0-beta5.tar.gz
http://www.boriel.com/files/zxb/zxbasic-1.10.0-beta5.zip

**Comment by Ultrahead** [comment] 2020-05-10 22:53
@boriel it compiles!!! Thanks a lot!

@Dotneteer in the last build the emulator stopped working. I'm reinstalling to see if that fixes it.

**Comment by Ultrahead** [comment] 2020-05-10 23:00
Reinstalled preview6 and I get the following exception:

```
SpectNetIdePackage initialized.
New active project: C:\Users\pedro\source\repos\SpectrumCodeDiscovery2\SpectrumCodeDiscovery2\SpectrumCodeDiscovery2.z80cdproj
Exception occured in SpectNetIde: Object reference not set to an instance of an object.
Full message: $System.NullReferenceException: Object reference not set to an instance of an object.
   at Spect.Net.VsPackage.ToolWindows.Disassembly.DisassemblyToolWindowViewModel.CreateDisassembler() in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\Disassembly\DisassemblyToolWindowViewModel.cs:line 609
   at Spect.Net.VsPackage.ToolWindows.Disassembly.DisassemblyToolWindowViewModel.Disassemble(ObservableCollection`1& disItems, Dictionary`2& lineIndexes) in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\Disassembly\DisassemblyToolWindowViewModel.cs:line 893
   at Spect.Net.VsPackage.ToolWindows.Disassembly.DisassemblyToolWindowViewModel.Disassemble() in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\Disassembly\DisassemblyToolWindowViewModel.cs:line 99
   at Spect.Net.VsPackage.ToolWindows.Disassembly.DisassemblyToolWindowViewModel.InitViewMode() in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\Disassembly\DisassemblyToolWindowViewModel.cs:line 497
   at Spect.Net.VsPackage.ToolWindows.BankAware.BankAwareToolWindowViewModelBase.SetFullViewMode() in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\BankAware\BankAwareToolWindowViewModelBase.cs:line 154
   at Spect.Net.VsPackage.ToolWindows.Disassembly.DisassemblyToolWindowViewModel.OnFirstStart() in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\Disassembly\DisassemblyToolWindowViewModel.cs:line 524
   at Spect.Net.VsPackage.ToolWindows.SpectrumToolWindowViewModelBase.OnInternalVmStateChanged(Object sender, VmStateChangedEventArgs e) in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\SpectrumToolWindowViewModelBase.cs:line 136
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Spect.Net.VsPackage.ToolWindows.SpectrumEmulator.EmulatorViewModel.OnVmStateChanged(Object sender, VmStateChangedEventArgs e) in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\SpectrumEmulator\EmulatorViewModel.cs:line 275
   at Spect.Net.SpectrumEmu.Machine.SpectrumMachine.OnVmStateChanged(VmStateChangedEventArgs e)
   at Spect.Net.SpectrumEmu.Machine.SpectrumMachine.set_MachineState(VmState value)
   at Spect.Net.SpectrumEmu.Machine.SpectrumMachine.StartWithOptions(ExecuteCycleOptions options)
   at Spect.Net.SpectrumEmu.Machine.SpectrumMachine.Start()
   at Spect.Net.VsPackage.ToolWindows.SpectrumEmulator.SpectrumEmulatorToolWindow.StartVmCommand.ExecuteOnMainThreadAsync() in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\ToolWindows\SpectrumEmulator\SpectrumEmulatorToolWindow.cs:line 112
   at Spect.Net.VsPackage.VsxLibrary.Command.SpectNetCommandBase.<OnExecute>d__27.MoveNext() in C:\Users\dotne\source\repos\spectnetide\v2\VsIntegration\Spect.Net.VsPackage\VsxLibrary\Command\SpectNetCommandBase.cs:line 146
```

**Comment by Ultrahead** [comment] 2020-05-10 23:05
Same result with custom package

**Comment by Ultrahead** [comment] 2020-05-10 23:27
It works with a new project.

@Dotneteer I will send you by PM the project that throws the exception.

**Comment by Dotneteer** [comment] 2020-05-11 13:16
Pedro,

How can I reproduce the issue with the project you sent me? When I start the Spectrum emulator, it works for me…

Nonetheless, according to the error message I suspect something that may cause the issue:

Visit the original folder of the project you just sent me. There must be folder named `.SpectNetIde`, where the IDE caches information. If VS 2019/SpectNetIDE crashes for any reason, files in this folder may become corrupted, and next time you try to run a project, the corrupted file may break the emulator.

The solution is easy:
1. Stop VS 2019 
2. Remove the entire .SpectNetIde folder from your solution
3. Restart VS 2019 and open your project.

Please, try these steps with your crashing solution!

**Comment by Dotneteer** [comment] 2020-05-11 13:35
Pedro,

Here is the fix that solved the issues with displaying UDG characters in the BASIC listings:

[Spect.Net.VsPackage.zip](https://github.com/Dotneteer/spectnetide/files/4609880/Spect.Net.VsPackage.zip)

**Comment by Ultrahead** [comment] 2020-05-11 18:20
It works perfectly. Given the heads up by José the exporter would have two options: 

A) Mimic ZX Basic (Optimal mode)
B) Mimic ZX Basic (Compatible mode)

Being the later the once that adds the --sinclair parameter value.

Regarding the project, my idea was that you double check my finding, but maybe I sent the incorrect project? Because "SpectrumCodeDiscovery2" has no .SpectNetIde folder in the solution. Could you please check if that is the project I sent?

**Comment by Dotneteer** [comment] 2020-05-13 05:52
Features and fixes released in Preview 8.

**Closed by Dotneteer** 2020-05-13 05:52 UTC
Labels: enhancement, in progress

**Comment by Ultrahead** [comment] 2020-05-13 10:38
Great! Besides this feature, what other things have been added in this preview?

**Comment by Dotneteer** [comment] 2020-05-13 10:56
Pedro,

You can find them here: https://github.com/Dotneteer/spectnetide/blob/master/CHANGELOG.md

Istvan

**Comment by Ultrahead** [comment] 2020-05-13 10:59
I've just noticed that I had a typo in a previous comment. It should read:

"Given the heads up by José the compiler settings should have two options for ZX Basic:

A) Mimic ZX Basic (Optimal mode)
B) Mimic ZX Basic (Compatible mode)"

Edited
