### ISSUE TITLE
Unable to install 1.16 update

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#113] opened 2019-02-14 01:58 UTC
Attempting to upgrade from 1.15 to 1.16 using the Extensions and Updates window in VS2017 fails. The window just instantly closes when you click "Update".   

Removing 1.15 and attempting a clean install of 1.16 results in the following error message:

"The extension could not be installed because the following error occurred:   The remote server returned an error: (500) Internal Server Error."  

Installing any other add-on works, however, so it looks like it's the host where SpectNet's files are stored perhaps?

**Comment by Dotneteer** [comment] 2019-02-14 05:13
About 3 hours after you, I still get the same error message. It must be either a Visual Studio error or a temporary Visual Studio Marketplace error.
Nonetheless, you can download the install kit from Visual Studio Markeptplace directly: https://marketplace.visualstudio.com/items?itemName=Dotneteer.SpectNetIde
After that you can run the VSIX file to install SpectNetIDE. I tried and it worked.
I notify the support team about the server error.

**Comment by Dotneteer** [comment] 2019-02-14 05:16
I've just read in an internal MVP mailing list that other users experienced the same issue with other extensions.

**Comment by Dotneteer** [comment] 2019-02-15 05:43
@nww02, The Microsoft Visual Studio Extensibility group confirmed that the issue is at their side, it seems nothing to do with SpectNetIDE itself. They working on resolving the issue.

**Comment by Dotneteer** [comment] 2019-02-15 13:48
@nww02, though I did not get an official answer yet, it seems so that the VSX team has resolved the Internal Server Issue. When I get the notification, I will close this issue.

**Closed** 2019-02-15 15:51 UTC

**Comment by nww02** [comment] 2019-02-15 23:45
Hurrah! How strange that it only affected some extensions and not others!  I'll be able to get coding again in the morning!

Thank you, sir!
