### ISSUE TITLE
Custom Project System missing 

### ISSUE THREAD

**Issue by timsneath** [Dotneteer/spectnetide#147] opened 2019-06-09 16:55 UTC
I performed a clean installation of Visual Studio 2019 (Community, v16.1.2) with no workloads installed. I then installed the SpectNet extension from the Extensions / Manage Extensions menu. 

On reloading Visual Studio, I got the following error message:

```
The 'SpectNetPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\tim\AppData\Roaming\Microsoft\VisualStudio\16.0_265a34a2\ActivityLog.xml'.

Restarting Visual Studio could help resolve this issue.
```

Inspecting `ActivityLog.xml` for items with a status of `Error`, we find this:
```
SetSite failed for package [SpectNetPackage]Source: 'mscorlib' Description: Could not find a part of the path 'C:\Users\tim\AppData\Local\CustomProjectSystems\Spect.Net.CodeDiscover\cps.version'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\tim\AppData\Local\CustomProjectSystems\Spect.Net.CodeDiscover\cps.version'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Spect.Net.VsPackage.SpectNetPackage.CheckCpsFiles()
   at Spect.Net.VsPackage.SpectNetPackage.<OnInitializeAsync>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Spect.Net.VsPackage.Vsx.VsxPackage.<InitializeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass19_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Services.VsTask.GetResult()
```

I've tried installing the .NET desktop and extensibility workloads, in case the core workload was missing a key component, but without luck. A search of my machine for the `CustomProjectSystems` folder doesn't show it as present either in this location or any other.

Any thoughts? 

Tim

**Comment by Dotneteer** [comment] 2019-06-09 19:12
Tim, thanks for contacting me about this issue. I have not checked SpectNetIDE with VS 2019 16.1.2, but now -- according to your report --, I will. Could you send me the version of SpectNetIDE you try to use with VS 2019?

Istvan

**Comment by Dotneteer** [comment] 2019-06-09 19:35
Tim, I managed to reproduce the issue. This issue occurs only if you remove SpectNetIDE and delete the `CustomProjectSystems` folder from use user profile directory -- and this is what a new install of VS 2019 does. The SpectNetIDE extension tries to create the `CustomProjectSystems` folder, but for some VS IDE related issue, it cannot do that.
Tomorrow I will examine the issue and release a patch that works with VS 2019 16.1.2 as soon as possible.

Istvan

**Comment by Dotneteer** [comment] 2019-06-10 05:27
Tim, I managed to find and fix the issue you reported. The cause of the phenomenon was due to changes in VS project system resource handling. Now, the freshly released SpectNetIDE v1.19.2 will solve it.

Istvan

**Comment by timsneath** [comment] 2019-06-10 16:16
Wow -- that was crazy fast! You fixed it before I'd even gotten back to my computer... Love that ZX Spectrum software is supported better than most modern software :) 

Thank you very much: what a labor of love. Will try this out this evening.

**Comment by Dotneteer** [comment] 2019-06-10 18:08
Tim, just let me know if you have any issues with the patch, or with SpectNetIDE. If your test show that now the package loads in VS 2019, please close this issue :-).

**Comment by timsneath** [comment] 2019-06-11 02:55
Good news, bad news... :)

So, I uninstalled VS2019 altogether, installed a fresh instance with just the core workload installed, and then installed 1.19.2 of SpectNetIDE. I got another extension load error, but the `ActivityLog.xml` entry this time gives a different warning:

```
SetSite failed for package [SpectNetPackage]Source: 'mscorlib' Description: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Spect.Net.VsPackage.Vsx.VsxPackage.ScanTypes(Func`2 condition, Action`1 action)
   at Spect.Net.VsPackage.Vsx.VsxPackage.<InitializeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass19_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.<JoinAsync>d__68.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Services.VsTask.GetResult()
```

This implies a missing dependency. So I added back the .NET desktop workload to my VS2019 instance, and then restarted Visual Studio. Now it loads without error, and the `ActivityLog.xml` file is missing, indicating no issues encountered. 

You could fix this in two ways, I think:

1. Make it very clear in the installation notes that the .NET desktop workload _must_ be installed for your extension to succeed;
2. Add a dependency in your VSIX manifest to require the specific components that you rely on, and the VSIX installer will automatically take care of ensuring that they're present.

The package references themselves are contained [here](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019).

The acid test of whether you've set up the dependencies correctly is whether you can successfully run your extension from the base of just a core editor installation. 

Again -- hope this is helpful! At least I'm unblocked for now: looking forward to experimenting with your extension now!

**Comment by Dotneteer** [comment] 2019-06-11 04:50
Tim, thanks for your help with the workload dependencies! I will experimenting them and find a decent solution :-).

**Closed by Dotneteer** 2019-06-11 04:50 UTC
