### ISSUE TITLE
Break points seem to cause problems if moved when running

### ISSUE THREAD

**Issue by nww02** [Dotneteer/spectnetide#92] opened 2019-01-18 03:00 UTC
When I'm running the code, to set a breakpoint I need to pause the program, set the breakpoint and then start the code running again.

Sometimes this has a few bad side-effects:

- having to pause/unpause the program adds unwanted steps.
- the breakpoint circle symbols vanish (although the breakpoint is still there)
- the highlighting stops working correctly.  When you're stopped at a breakpoint, all the breakpoints are the same (not-activated) red colour, even the one you're broken into the program at.

**Comment by Dotneteer** [comment] 2019-01-18 07:58
Examining the issue...

**Comment by nww02** [comment] 2019-01-19 00:39
Thanks.    It's happened quite a few times.  I only have some small apps, but over time, with the moving around of breakpoints, at some point the code will stop, and the UI just seems to go a bit haywire.    Probably a VS bug :)

**Comment by Dotneteer** [comment] 2019-02-01 16:01
@nww02, I examined the issues you mentioned.
* I solved the pause/unpause issue, so now, you can set/clear a breakpoint while the code is running.
* The breakpoint circle seems to be a VS bug &mdash; I can reproduce it. In the code, I do not do any drawing, I simply receive the list of currently set breakpoints from the IDE.
* I try to find some fix for the highlighting issue,

I will release the changes along with the newly developed conditional breakpoints, hopefully in a few days :-).

**Comment by nww02** [comment] 2019-02-03 22:11
Ah, great! I'm glad you nailed down the issue.    So many bugs in VS2017!!!  I've stuck with VS2010 until I saw SpectNetIDE used '17.     Thanks for the fixes!  Looking forward to the next release :)

**Comment by Dotneteer** [comment] 2019-02-04 07:55
Fixed in v1.15.0. I could improve a bit on the highlight colors, but was unable to find the sources of the VS bug.

**Closed by Dotneteer** 2019-02-04 07:55 UTC
Labels: in progress
