### ISSUE TITLE
Debug does not follow current line

### ISSUE THREAD

**Issue by gusmanb** [Dotneteer/spectnetide#170] opened 2020-02-02 11:11 UTC
Hi.

I'm testing the V2 preview 4 (great job btw!)  and I have found that debug does not highlight the current line. I'm debugging a ZX Basic program, it contains embedded ASM and is that function the one I'm trying to debug.

To enable the debug I place the break point on the .z80asm generated file and then start debugging the z80asm file (I also have tried starting the zxbas one). The breakpoint gets hit and the line changes it's color to orange but then when I press "Step into" on the emulator window the highlight isn't displaced. I see how the code scrolls up but the highlight is kept on the breakpoint line and there's no other visual indicator.

Am I missing something?

**Comment by Dotneteer** [comment] 2020-02-05 13:07
@gusmanb, sorry for my slow answer, I was on trip... I do not think you miss something, it looks like a bug. You could help me a lot by sending me a concrete project zipped and some instructions to reproduce the issue. During the weekend I try to catch and fix it. Thanks in advance!

**Comment by gusmanb** [comment] 2020-02-05 14:56
Hi!

The thing is that I have been working on the project all the week and now I'm unable to reproduce it, after two days I gave it another try and it worked and since then it hasn't failed a single time...

The program is part of a bigger solution that I have published on Github so if you want you can download it. The project is here:  https://github.com/gusmanb/zxshield
And the concrete file with the afore mentioned function is this : https://github.com/gusmanb/zxshield/blob/master/ZXTelnet/ZxBasicFiles/RegisterFunctions.zxbas

If it happens again I will try to get compilation logs and a list of actions I take to happen.

BTW, not sure if you remember the changes I asked you for creating ROM's, just want to say THANKS, it has been crucial for the project, after a long time finally I had enough spare time to implement it and thanks to these I have evolved the idea to something a lot more useful, the ZXShield.

Cheers!

**Comment by Dotneteer** [comment] 2020-02-05 15:03
@gusmanb, thanks for the info, I try to reproduce the behavior.

Congrats for ZXShield! If you have any new feature idea that can be useful for you, do not hesitate and share with me!

I'm pampering the idea of creating a new independent, multi-platform ZX Spectrum IDE with the style of Visual Studio *Code* (but without its UI limitations). When I have any news, I will publish them.

**Comment by gusmanb** [comment] 2020-02-05 23:50
Really nice! SpectnetIDE as a standalone can become a standard for ZX Spectrum development, is the best IDE/toolchain I have tried by far :D

I have reproduced the problem but not 100% sure how. This time has happened in a .z80asm regular file, not a basic one. I was debugging normally and I think I have closed the emulator once or twice and then the next time I have tried to debug the emulator paused correctly on the breakpoint I had but the code window did not got activated and no line has been highlighted.

Also, I remember I changed the ORG address (was XXX, executed, closed debugger, changed ORG, started debug, problem arised)

I don't know which logs would help you so I have taken a screenshot with all the debug windows in it.

https://imgur.com/a/x8t2ymJ

Also, I have uploaded the project, it's a new project with 10 lines of ASM, nothing else.

https://mega.nz/#!aHwwySwR!Uial-1eLe_Q1pTaOejBW5GLA_fYc-eXHMbg1nVotHRc

Is there anything else that I can add if it happens again?

**Comment by Dotneteer** [comment] 2020-02-09 06:38
@gusman, I managed to find a reproducable scenario, and fixed the bug. The fix will be released in v2 Preview 5.

**Comment by gusmanb** [comment] 2020-02-09 19:18
Nice!

**Comment by gusmanb** [comment] 2020-02-16 00:07
I have been testing the private build and for now it seems to work perfectly :)

I will test it intensively next week as I'm on the middle of a ZXBasic project and if I find any problem will report it.

Cheers!

**Comment by Dotneteer** [comment] 2020-02-18 06:32
Released in v2 Preview 5.

**Closed by Dotneteer** 2020-02-18 06:32 UTC
Labels: in progress
