### ISSUE TITLE
Extension starting issue

### ISSUE THREAD

**Issue by miocr** [Dotneteer/spectnetide#77] opened 2018-10-04 21:33 UTC
Hi, I install specnetide extension. When Visual Studio 2017 starts, this error message appears 

---------------------------
The 'SpectNetPackage' package did not load correctly.
The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\User\AppData\Roaming\Microsoft\VisualStudio\15.0_460adfb2\ActivityLog.xml'.
---------------------------

Corresponding lines from ActivityLog.xml: 

190 |   | Begin package load [SpectNetPackage] | {1B214806-BC31-49BD-BE5D-79AC4A189F3C} |   | VisualStudio | 2018/10/04 21:18:17.869
-- | -- | -- | -- | -- | -- | --
191 | ERROR | SetSite failed for package [SpectNetPackage]Source: 'mscorlib' Description: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)   at System.Reflection.RuntimeModule.GetTypes()   at System.Reflection.Assembly.GetTypes()   at Spect.Net.VsPackage.Vsx.VsxPackage.ScanTypes(Func`2 condition, Action`1 action) in C:\Users\dotne\Source\Repos\spectnetide\VsIntegration\Spect.Net.VsPackage\Vsx\VsxPackage.cs:line 197   at Spect.Net.VsPackage.Vsx.VsxPackage.<InitializeAsync>d__13.MoveNext() in C:\Users\dotne\Source\Repos\spectnetide\VsIntegration\Spect.Net.VsPackage\Vsx\VsxPackage.cs:line 87 --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass17_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)   at Microsoft.VisualStudio.Services.VsTask.GetResult() | {1B214806-BC31-49BD-BE5D-79AC4A189F3C} | 80131602 | VisualStudio | 2018/10/04 21:18:18.009
192 | ERROR | End package load [SpectNetPackage] | {1B214806-BC31-49BD-BE5D-79AC4A189F3C} | 80131602 | VisualStudio | 2018/10/04 21:18:18.025
193 |   | Entering function CVsPackageInfo::HrInstantiatePackage

**Comment by Dotneteer** [comment] 2018-10-05 06:07
@miocr , please send me the version number of Visual Studio you use. IS this version a fresh installation, or you have been using VS 2017 for a longer time on your machine?

**Comment by miocr** [comment] 2018-10-05 08:07
@Dotneteer Hi, I have 2 computers. Both systems I use longer time and VS also (VS 2017 for over a year). On machine first (Desktop with Win10Pro CZ) spectnetide works well. On second machine (NB with Win7Pro CZ) spectnetide does not work - reported issue. Both OS are set to Czech language.  Your spectnetide  extension is excellent! I would also like to use it on the second machine (NB). I'm a big fan of ZX :-)

**Comment by Dotneteer** [comment] 2018-10-05 10:56
@miocr, thanks for the extra info :-). I guess, it must be something in regard to CZ Windows. You seem to be the second reporting the similar issue (see #76, which reports the issue on Spanish VS 2017). Now, I have some clues where to start finding the issue...

**Comment by Dotneteer** [comment] 2018-10-07 06:40
@miocr, right now it seems (difficult to reproduce) that issue is Windows 7. I try to reproduce the issue on a virtual machine. I need one piece of information from you: did you install the SpectNetIde extension from Visual Studio Marketplace, or you used the downloaded source code to compile and run it on Windows 7?

**Comment by Dotneteer** [comment] 2018-10-07 08:45
@miocr, Thanks for the info. I will fix the issue with quotes in the post building event. I still did not manage to reproduce the issue. It is a good sign that the locally compiled package works :-).

**Comment by Dotneteer** [comment] 2018-10-07 13:11
@miocr, please, send me your email address to dotneteer@hotmail.com, I'd like to share a private build with you for test!

**Comment by Dotneteer** [comment] 2018-10-07 17:08
Thanks to @miocr for helping in the resolution. I did not manage to identify exactly what the reason of this issue was (it occurred on Windows 7 with non-English display language). Building the source with VS version 15.8.6 solved the issue. The fix is released in SpectNetIde 1.10.3

**Comment by p3365** [comment] 2018-12-30 10:31
This issue is happening on my system (Windows 10 Pro). I downloaded this extension today and installed this extension into VS 2017 Community Edition. It fails to start with the error as shown above.

The 'SpectNetPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\Paul\AppData\Roaming\Microsoft\VisualStudio\15.0_e3f76dba\ActivityLog.xml'.
Restarting Visual Studio could help resolve this issue.
Continue to show this error message?

The full exception text is in the attached file: [ActivityLog.xml](https://github.com/Dotneteer/spectnetide/files/2717058/ActivityLog.xml.txt)

**Comment by Dotneteer** [comment] 2018-12-30 12:53
@p3365 , as you can see from the comment-snake above, I was unable to reproduce the issue. Please, share a few details about your environment! 
* VS version number (in Help|About)
* Your Windows version and language

I exactly know the code line that raises this issue, but do not really find the rationale behind... Hopefully, the info you send me may help.

It also would be great, if you contact me at dotneteer@hotmail.com directly, so that I'll be able to send you private build(s) that you can test.

Thanks in advance,
Istvan

**Comment by p3365** [comment] 2018-12-30 13:12
Hi Istvan. I was running against the vanilla version of VS 2017 (15.0.0). I updated to the latest version (15.9) and it now works correctly without any errors. It's a bit strange, perhaps if you install that version you would also get some errors? I have a couple more laptops, maybe I could reproduce it on one of these?

**Comment by p3365** [comment] 2018-12-30 13:13
Its Windows 10 Pro, US English

**Comment by Dotneteer** [comment] 2018-12-30 13:33
Hi @p3365, 

Your explanation helped me to understand that the issue was version 15.0.0. Unfortunately, SpectNetIDE does not work with that version anymore :-(. I know, it's strange, here's a short explanation:

From VS extensions point of view, 15.9 is very different from 15.0. The Visual Studio Extensibility (VSX) team continuously improves (changes) the IDE, and sometimes it means breaking compatibility on particular areas. My SpectNetIDE extension uses such a nasty feature: a custom project system. This area is extremely poorly documented.

From SpectNetIDE's point of view, the other significant difference between 15.0 and 15.9 is extension loading. In 15.0 it was synchronous, from 15.6 it is async. For a few months, the Visual Studio Marketplace allows publishing only asynchronously loading packages.

I just do not have enough time to take care of long backward compatibility -- I'd like to spend my resources on adding new features. According to community feedback, SpectNetIDE works with the latest two or three minor versions of Visual Studio.

I even have not start dealing with VS 2019 yet...

**Comment by p3365** [comment] 2018-12-30 14:01
Thanks. I think it would be good if your extension refuses to install on VS minor versions that are not compatible. I am not sure if you can make it do that, does the VS environment support it?

**Comment by Dotneteer** [comment] 2018-12-30 14:07
Yes, that is possible. I can restrict the environments the VSIX installer will setup the extension. I will add this modification to my backlog :-). May I close the issue?

**Comment by p3365** [comment] 2018-12-30 14:10
As a fellow software architect I would only close an issue when it's been fixed and released ;-)

But yes, you can close the issue!

**Comment by Dotneteer** [comment] 2018-12-30 14:13
You're right :-). I will keep close it when releasing the fix...

**Comment by Dotneteer** [comment] 2018-12-30 17:00
Hi @p3365, 

Unfortunately, restricting a Visual Studio extension to a minor version should be possible, but it does not work. (I experienced exactly the same phenomenon as described here: https://stackoverflow.com/questions/53178743/how-to-specify-vspackage-vsix-manifest-prereq-or-install-target-version-range). Whether it is a bug or a feature, a do not know :-(. I contact the VSX team and try to get some info from them.

**Comment by p3365** [comment] 2018-12-30 17:45
Have you seen https://docs.microsoft.com/en-us/nuget/reference/package-versioning? You should be able to use brackets and asterisks to say, for example, '15.8 and newer' versions of VS.

**Comment by p3365** [comment] 2018-12-30 17:47
I know this link refers to nuget, but the syntax in the Stackoverflow article seems to imply the same syntax and semantics.

**Comment by Dotneteer** [comment] 2019-01-15 07:53
I was unable to find a solution for this issue, so I close it. I March I'll be in Redmond, and try to discuss the issue personally with the VSX team.

**Closed by Dotneteer** 2019-01-15 07:53 UTC
